version: '3.7'

services:
  mysql:
    container_name: ninjas-mysql
    image: ninjas-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # MYSQL_DATABASE: ninja
    networks:
      - ninjas-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: ninjas-app
    image: ninjas-app
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - ninjas-network

networks:
  ninjas-network:
 