openapi: 3.0.0
info:
  title: Ninjas
  version: 0.0.1
  description: 'An example REST API'
  contact:
    name: my student id
    email: my.student.email@intitution.country
servers:
- url: http://localhost:8080
  description: My localhost
  variables:
    basePath:
      default: /
paths:
  '/lessons':
    get:
      tags:
        - LessonsController
      operationId: retrieveLessons
      summary: Retrieve lessons
      responses:
        '200':
          description: Array of lessons model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesson'
            application/xml:
              schema:
                type: object
                xml:
                  name: Lessons
                properties:
                  Lesson:
                    type: array
                    items:
                      $ref: '#/components/schemas/Lesson'
                  
    post:
      tags:
      - LessonsController
      operationId: createLesson
      summary: Create lesson
      responses:
        "200":
          description: Create a Lesson model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
            application/xml:
              schema:
                $ref: '#/components/schemas/Lesson'
        "400":
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lesson'
            examples:
              LessonExample01:
                $ref: '#/components/examples/LessonExample01'
              LessonExample02:
                $ref: '#/components/examples/LessonExample02'
          application/xml:
            schema:
              $ref: '#/components/schemas/Lesson'
            examples:
              LessonExample01:
                $ref: '#/components/examples/LessonExample01'
              LessonExample02:
                $ref: '#/components/examples/LessonExample02'
  '/lessons/{id}':
    get:
      tags:
        - LessonsController
      operationId: retrieveLesson
      summary: Retrieve lesson
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
            application/xml:
              schema:
                $ref: '#/components/schemas/Lesson'
        "400":
          description: Bad request
        "404":
          description: id not found
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
            minimum: 1
          required: true
          examples:
            one: 
              value: 1
              summary: Retrieve Lesson id 1
            two:
              value: 2
              summary: Retrieve Lesson id 2
    put:
      tags:
        - LessonsController
      operationId: updateLesson
      summary: Update lesson
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                description: Lesson PUT success
        "400":
          description: Bad request
        "404":
          description: id not found
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
            minimum: 1
          required: true
          examples:
            one: 
              value: 1
              summary: Update Lesson id 1
            two:
              value: 2
              summary: Update Lesson id 2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lesson'
            examples:
              AeroportoExample01:
                $ref: '#/components/examples/LessonExample01'
              AeroportoExample02:
                $ref: '#/components/examples/LessonExample02'
    delete:
      tags:
        - LessonsController
      operationId: deleteLesson
      summary: Delete lesson
      responses:
        '204':
          description: No Content
        "404": 
          description: id not found
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
            minimum: 1
          required: true
          examples:
            one: 
              value: 1
              summary: Delete Lesson id 1
            two:
              value: 2
              summary: Delete Lesson id 2
  '/ninjas':
    get:
      tags:
        - NinjasController
      operationId: retrieveNinjas
      summary: Retrieve ninjas
      responses:
        '200':
          description: Array of Ninja model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ninja'
            application/xml:
              schema:
                type: object
                xml:
                  name: ninjas
                properties:
                  Ninja:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ninja'
    post:
      tags:
        - NinjasController
      operationId: createNinja
      summary: Create ninja
      responses:
        '200':
          description: Create a Ninja model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ninja'
            application/xml:
              schema:
                $ref: '#/components/schemas/Ninja'
        "400":
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ninja'
          application/xml:
            schema:
              $ref: '#/components/schemas/Ninja'
  '/ninjas/{id}':
    get:
      tags:
        - NinjasController
      operationId: retrieveNinja
      summary: Retrieve ninja
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ninja'
            application/xml:
              schema:
                $ref: '#/components/schemas/Ninja'
        "400":
          description: Bad request
        "404":
          description: id not found
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
            minimum: 1
          required: true
          examples:
            one: 
              value: 1
              summary: Retrieve Ninja id 1
            two:
              value: 2
              summary: Retrieve Ninja id 2
    put:
      tags:
        - NinjasController
      operationId: updateNinja
      summary: Update ninja
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                description: Ninja PUT success
        "400":
          description: Bad request
        "404":
          description: id not found
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
            minimum: 1
          required: true
          examples:
            one: 
              value: 1
              summary: Update Ninja id 1
            two:
              value: 2
              summary: Update Ninja id 2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ninja'
            examples:
              AeroportoExample01:
                $ref: '#/components/examples/NinjaExample01'
              AeroportoExample02:
                $ref: '#/components/examples/NinjaExample02'
    delete:
      tags:
        - NinjasController
      operationId: deleteNinja
      summary: Delete ninja
      responses:
        '204':
          description: No Content
        "404": 
          description: id not found
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
            minimum: 1
          required: true
          examples:
            one: 
              value: 1
              summary: Delete Ninja id 1
            two:
              value: 2
              summary: Delete Ninja id 2
components:
  schemas:
    Ninja:
      title: Ninja
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        color:
          type: string
      required:
        - name 
        - description
      additionalProperties: false
    Lesson:
      title: Lesson
      type: object
      properties:
        id:
          type: integer
          format: int64
        subject:
          type: string
        course: 
          type: string
        year:
          type: integer
          format: int32
        group:
          type: string
        room:
          type: string
        date:
          type: string
          format: date
        time:
          type: string
          format: time
        duration: 
          type: integer
      required:
        - date
        - time
        - duration
      additionalProperties: false
  examples:
    NinjaExample01:
      value:
        id: 1
        name: Ninja 01
        description: My ninja for this year
        color: #00cc00
    NinjaExample02:
      value:
        id: 2
        name: Ninja 02
        description: My ninja for next year
        color: #0000cc
    LessonExample01:
      value:
        id: 1
        subject: Web programming
        course: Informatics
        year: 2
        group: A
        room: Lab.04
        date: "2021-02-24"
        time: "10:15:00"
        duration: 2
    LessonExample02:
      value:
        id: 2
        subject: Web programming
        course: Informatics
        year: 2
        group: B
        room: Lab.08
        date: "2021-03-01"
        time: "18:15:00"
        duration: 2